# Project information
site_name: Vellox
site_url: http://vellox.junah.dev
site_author: Junah Kim
site_description: GCP Cloud Functions support for ASGI applications

# Repository
repo_name: junah201/vellox
repo_url: https://github.com/junah201/vellox

# Copyright
copyright: Copyright &copy; 2024 Junah Kim

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# Page tree
nav:
  - Introduction: "index.md"
  - Adapter: "adapter.md"
  - HTTP: "http.md"
  - Lifespan: "lifespan.md"
  - ASGI Frameworks: "asgi-frameworks.md"
  - External Links: "external-links.md"
  - Contributing: "contributing.md"

# Extensions
markdown_extensions:
  - mkautodoc
  - markdown.extensions.codehilite:
      guess_lang: false
